[feat][bif][v0.1-SNAPSHOT] support bif chain bbc plugin
AntChainOpenLabs/AntChainBridge pull request #36
Opened 2024-05-15 11:38 UTC by Curious-Yc

2024-05-17 03:56 UTC, zouxyan requested changes

2024-05-17 03:56 UTC, zouxyan commented on pluginset/bifchain/offchain-plugin/src/main/java/com/alipay/antchain/bridge/plugins/bifchain/AuthMsg.java
> +    ;
这是不是多余的分号

2024-05-17 03:56 UTC, zouxyan commented on pluginset/bifchain/offchain-plugin/src/main/java/com/alipay/antchain/bridge/plugins/bifchain/BifchainBBCService.java
> +        System.out.println("start up service");
[示例](https://github.com/AntChainOpenLabs/AntChainBridgePluginSDK/blob/14eeaf4404cd03b76dd9e3160f3d62534e723c75/pluginset/ethereum/offchain-plugin/src/main/java/com/alipay/antchain/bridge/plugins/ethereum/EthereumBBCService.java#L61)

可以这样打印日志，通过`getBBCLogger()`，插件服务会注入Logger，实现日志管理，需要继承`AbstractBBCService`。

2024-05-17 03:56 UTC, zouxyan commented on pluginset/bifchain/offchain-plugin/src/main/java/com/alipay/antchain/bridge/plugins/bifchain/BifchainBBCService.java
> +                Thread.sleep(1000L);
最好是先查询，再sleep吧，万一查到了呢

2024-05-17 03:56 UTC, zouxyan commented on pluginset/bifchain/offchain-plugin/src/main/java/com/alipay/antchain/bridge/plugins/bifchain/BifchainBBCService.java
> +            String payload = "608060405234801562000010575f80fd5b505f620000226200011c60201b60201c565b9050805f806101000a81548177ffffffffffffffffffffffffffffffffffffffffffffffff021916908377fffffffffffff
可以整个字节码的静态变量，不要在函数局部变量这样赋值，貌似这样使用了栈的内存，静态变量会放在jvm的堆里

2024-05-17 03:56 UTC, zouxyan commented on pluginset/bifchain/offchain-plugin/src/main/java/com/alipay/antchain/bridge/plugins/bifchain/BifchainBBCService.java
> +            String payload = "608060405234801562000010575f80fd5b505f62000022620000d460201b60201c565b9050805f806101000a81548177ffffffffffffffffffffffffffffffffffffffffffffffff021916908377fffffffffffff
可以整个字节码的静态变量，不要在函数局部变量这样赋值，貌似这样使用了栈的内存，静态变量会放在jvm的堆里

2024-05-17 03:56 UTC, zouxyan commented on pluginset/bifchain/offchain-plugin/src/main/java/com/alipay/antchain/bridge/plugins/bifchain/BifchainBBCService.java
> +            BIFContractInvokeResponse response = sdk.getBIFContractService().contractInvoke(request);
这里是同步发送交易吗，就是拿到response的时候，交易已经在链上落帐了，如果是的话，可以将confirmed设置为true：`crossChainMessageReceipt.setConfirmed(true);`

2024-05-17 03:56 UTC, zouxyan commented on pluginset/bifchain/offchain-plugin/src/main/java/com/alipay/antchain/bridge/plugins/bifchain/BifchainBBCService.java
> +                throw new RuntimeException("failed to relay auth message, transaction sending failed");
如果合约调用失败，建议不要抛出异常，而是在crossChainMessageReceipt中标记successful为false，set好error msg返回

2024-05-17 03:56 UTC, zouxyan commented on pluginset/bifchain/offchain-plugin/src/main/java/com/alipay/antchain/bridge/plugins/bifchain/BifchainBBCService.java
> +                            String topic = bifTransactionGetInfoResponse.getResult().getTransactions()[0].getTransaction().getOperations()[0].getLog().getTopic();
交易里只会有一个事件么，我看直接取的第一个

2024-05-17 03:56 UTC, zouxyan commented on pluginset/bifchain/offchain-plugin/src/main/java/com/alipay/antchain/bridge/plugins/bifchain/BifchainBBCService.java
> +                            if (topic.equals("79b7516b1b7a6a39fb4b7b22e8667cd3744e5c27425292f8a9f49d1042c0c651")) {
除了topic相等之外，还要求产生Log的合约是context里面的AM合约，因为链上可能有多本AM合约，这样的话，可能抓到了别的AM合约的消息

2024-05-17 03:56 UTC, zouxyan commented on pluginset/bifchain/offchain-plugin/src/main/java/com/alipay/antchain/bridge/plugins/bifchain/BifchainBBCService.java
> +                                        lockGetInfoResponse.getResult().getHeader().getHash().getBytes(),
这里预期是32bytes，就是Hex decode一下getHash的返回：
```
HexUtil.decodeHex(StrUtil.removePrefix(lockGetInfoResponse.getResult().getHeader().getHash(), "0x"))
```

2024-05-24 09:50 UTC, zouxyan commented on pluginset/bifchain/offchain-plugin/src/main/java/com/alipay/antchain/bridge/plugins/bifchain/BifchainBBCService.java
> +                crossChainMessageReceipt.setConfirmed(false);
交易上链了，也就是被区块打包了，confirm为true，但是error code 不是零，是不是就是交易revert了，这时候可以返回 confirm为true、successful为false。
增加代码处理一下这种情况吧

2024-05-27 01:39 UTC, Curious-Yc commented on pluginset/bifchain/offchain-plugin/src/main/java/com/alipay/antchain/bridge/plugins/bifchain/BifchainBBCService.java
> +                Thread.sleep(1000L);
已采用先查询后sleep

2024-05-27 01:40 UTC, Curious-Yc commented on pluginset/bifchain/offchain-plugin/src/main/java/com/alipay/antchain/bridge/plugins/bifchain/BifchainBBCService.java
> +            String payload = "608060405234801562000010575f80fd5b505f62000022620000d460201b60201c565b9050805f806101000a81548177ffffffffffffffffffffffffffffffffffffffffffffffff021916908377fffffffffffff
已采用静态变量

2024-05-27 01:40 UTC, Curious-Yc commented on pluginset/bifchain/offchain-plugin/src/main/java/com/alipay/antchain/bridge/plugins/bifchain/BifchainBBCService.java
> +                throw new RuntimeException("failed to relay auth message, transaction sending failed");
已采纳

2024-05-27 01:46 UTC, Curious-Yc commented on pluginset/bifchain/offchain-plugin/src/main/java/com/alipay/antchain/bridge/plugins/bifchain/BifchainBBCService.java
> +            String payload = "608060405234801562000010575f80fd5b505f620000226200011c60201b60201c565b9050805f806101000a81548177ffffffffffffffffffffffffffffffffffffffffffffffff021916908377fffffffffffff
已采纳建议

2024-06-12 07:42 UTC, zouxyan approved these changes

2024-06-12 07:42 UTC, merged